<script lang="ts">
	let {} = $props();
</script>

<div class="p-4 w-full overflow-y-auto">
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
	<p class="text-4xl">Report stats</p>
</div>
